/*
 *
 * PatientAppointments constants
 *
 */

/**
 *  PatientAppointments action types
 *  @type {string}
 */
export const DEFAULT_ACTION = 'ocpui/PatientAppointments/DEFAULT_ACTION';
export const INITIALIZE_PATIENT_APPOINTMENTS = 'ocpui/PatientAppointments/INITIALIZE_PATIENT_APPOINTMENTS';
export const GET_PATIENT_APPOINTMENTS = 'ocpui/PatientAppointments/GET_PATIENT_APPOINTMENTS';
export const GET_PATIENT_APPOINTMENTS_SUCCESS = 'ocpui/PatientAppointments/GET_PATIENT_APPOINTMENTS_SUCCESS';
export const GET_PATIENT_APPOINTMENTS_ERROR = 'ocpui/PatientAppointments/GET_PATIENT_APPOINTMENTS_ERROR';

export const CANCEL_PATIENT_APPOINTMENT = 'ocpui/PatientAppointments/CANCEL_PATIENT_APPOINTMENT';
export const CANCEL_PATIENT_APPOINTMENT_SUCCESS = 'ocpui/PatientAppointments/CANCEL_PATIENT_APPOINTMENT_SUCCESS';
export const CANCEL_PATIENT_APPOINTMENT_ERROR = 'ocpui/PatientAppointments/CANCEL_PATIENT_APPOINTMENT_ERROR';

export const ACCEPT_PATIENT_APPOINTMENT = 'ocpui/PatientAppointments/ACCEPT_PATIENT_APPOINTMENT';
export const ACCEPT_PATIENT_APPOINTMENT_SUCCESS = 'ocpui/PatientAppointments/ACCEPT_PATIENT_APPOINTMENT_SUCCESS';
export const ACCEPT_PATIENT_APPOINTMENT_ERROR = 'ocpui/PatientAppointments/ACCEPT_PATIENT_APPOINTMENT_ERROR';

export const DECLINE_PATIENT_APPOINTMENT = 'ocpui/PatientAppointments/DECLINE_PATIENT_APPOINTMENT';
export const DECLINE_PATIENT_APPOINTMENT_SUCCESS = 'ocpui/PatientAppointments/DECLINE_PATIENT_APPOINTMENT_SUCCESS';
export const DECLINE_PATIENT_APPOINTMENT_ERROR = 'ocpui/PatientAppointments/DECLINE_PATIENT_APPOINTMENT_ERROR';

export const TENTATIVE_PATIENT_APPOINTMENT = 'ocpui/PatientAppointments/TENTATIVE_PATIENT_APPOINTMENT';
export const TENTATIVE_PATIENT_APPOINTMENT_SUCCESS = 'ocpui/PatientAppointments/TENTATIVE_PATIENT_APPOINTMENT_SUCCESS';
export const TENTATIVE_PATIENT_APPOINTMENT_ERROR = 'ocpui/PatientAppointments/TENTATIVE_PATIENT_APPOINTMENT_ERROR';

export const GET_APPOINTMENT_RELATED_COMMUNICATIONS = 'ocpui/PatientAppointments/GET_APPOINTMENT_RELATED_COMMUNICATIONS';
export const GET_APPOINTMENT_RELATED_COMMUNICATIONS_SUCCESS = 'ocpui/PatientAppointments/GET_APPOINTMENT_RELATED_COMMUNICATIONS_SUCCESS';
export const GET_APPOINTMENT_RELATED_COMMUNICATIONS_ERROR = 'ocpui/PatientAppointments/GET_APPOINTMENT_RELATED_COMMUNICATIONS_ERROR';
/**
 *  Other constants
 *
 */
export const LOADING = 'loading';
export const DATA = 'data';
export const STATUS_CODE_CANCELLED = 'cancelled';
