#!/bin/sh

echo "running replace_env_vars.sh"
printenv

REPLACING_DIR=./build/
if [ ! -d "$REPLACING_DIR" ]; then
    REPLACING_DIR=./env.js
fi

echo "REPLACING_DIR=$REPLACING_DIR"

# Replacing environment variables
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_ASSESSMENTS_SERVER_BASE_URL_,'"${REACT_APP_ASSESSMENTS_SERVER_BASE_URL}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_ASSESSMENT_INITIAL_INTERVIEW_,'"${REACT_APP_ASSESSMENT_INITIAL_INTERVIEW}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_PATIENT_IDENTIFIER_MEDICAID_ID_SYSTEM_,'"${REACT_APP_PATIENT_IDENTIFIER_MEDICAID_ID_SYSTEM}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_FHIR_INITIAL_INTERVIEW_ACTIVITY_DEFINITION_REF_,'"${REACT_APP_FHIR_INITIAL_INTERVIEW_ACTIVITY_DEFINITION_REF}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_KEYCLOAK_REDIRECT_URL_,'"${REACT_APP_KEYCLOAK_REDIRECT_URL}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_KEYCLOAK_LOGOUT_URL_,'"${REACT_APP_KEYCLOAK_LOGOUT_URL}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_BASE_FHIR_URL_,'"${REACT_APP_BASE_FHIR_URL}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_ENV_LABEL_,'"${REACT_APP_ENV_LABEL}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_ORG_ADMIN_DASHBOARD_HOST_URL_,'"${REACT_APP_ORG_ADMIN_DASHBOARD_HOST_URL}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_ORG_ADMIN_DASHBOARD_VIEW_NAME_,'"${REACT_APP_ORG_ADMIN_DASHBOARD_VIEW_NAME}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_CARE_MANAGER_DASHBOARD_HOST_URL_,'"${REACT_APP_CARE_MANAGER_DASHBOARD_HOST_URL}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_CARE_MANAGER_DASHBOARD_VIEW_NAME_,'"${REACT_APP_CARE_MANAGER_DASHBOARD_VIEW_NAME}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_CARE_COORDINATOR_DASHBOARD_HOST_URL_,'"${REACT_APP_CARE_COORDINATOR_DASHBOARD_HOST_URL}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_CARE_COORDINATOR_DASHBOARD_VIEW_NAME_,'"${REACT_APP_CARE_COORDINATOR_DASHBOARD_VIEW_NAME}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_ASSESSMENT_TOKEN_IDENTIFIER_SYSTEM_,'"${REACT_APP_ASSESSMENT_TOKEN_IDENTIFIER_SYSTEM}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_MAX_INACTIVITY_SECONDS_,'"${REACT_APP_MAX_INACTIVITY_SECONDS}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_TASK_SURVEY_GENERIC_TOKEN_GENERATOR_,'"${REACT_APP_TASK_SURVEY_GENERIC_TOKEN_GENERATOR}"',g' {} \;
find $REPLACING_DIR -name '*.js' -exec sed -i -e 's,_REACT_APP_TASK_DEFAULT_ACTIVITY_DEFINITION_REF_,'"${REACT_APP_TASK_DEFAULT_ACTIVITY_DEFINITION_REF}"',g' {} \;

